import openPack from "../data/packs/open.json";
import workbookPack from "../data/packs/workbook.json";

import type { Dataset, Poi, UserProfile } from "./types";

// Dataset packs. `workbook` is the frozen TASCO dataset the judged eval pins its
// POI IDs to — it must never be mutated by the open-data pipeline. `open` is the
// real-venue pack generated by scripts/pull-overture.mjs (+ BigSet enrichment).
// Selection happens ONCE at module load from the server environment; tests and
// the evaluator that need a specific pack import accessors that take an explicit
// pack instead of relying on the env.
export type PackName = "workbook" | "open";

const workbook = workbookPack as Dataset;
const open = openPack as unknown as Dataset;

export function getPack(name: PackName): Dataset {
  return name === "open" ? open : workbook;
}

export const activePackName: PackName =
  process.env.TASCO_DATASET_PACK === "open" ? "open" : "workbook";

// District lock: the TASCO-provided workbook ships venues in Hà Nội, Đà Nẵng,
// Đà Lạt, etc., but the demo story is strictly Quận 1 — without a fence the
// engine happily recommends a Đà Nẵng hotel. TASCO_DISTRICT_LOCK (set in the
// dev scripts) filters the SERVED dataset only; workbook.json itself stays
// frozen because the judged eval pins POI IDs across all cities and runs
// without the lock.
export const districtLock = process.env.TASCO_DISTRICT_LOCK?.trim() || undefined;

export function applyDistrictLock(dataset: Dataset, district: string | undefined): Dataset {
  if (!district) return dataset;
  return {
    ...dataset,
    pois: dataset.pois.filter((poi) => poi.district === district && poi.city === "TP.HCM"),
  };
}

export const dataset = applyDistrictLock(getPack(activePackName), districtLock);
export const pois: readonly Poi[] = dataset.pois;

// Profiles, workbook scenarios, and the public evaluation exist only in the
// workbook pack, regardless of which pack serves POIs.
export const userProfiles: readonly UserProfile[] = workbook.userProfiles;

const poiById = new Map(pois.map((poi) => [poi.id.toUpperCase(), poi]));
const profileById = new Map(
  userProfiles.map((profile) => [profile.id.toUpperCase(), profile]),
);

export function getPoiById(id: string): Poi | undefined {
  return poiById.get(id.toUpperCase());
}

export function getUserProfile(id?: string): UserProfile | undefined {
  return id ? profileById.get(id.toUpperCase()) : undefined;
}

// Home-screen and map seeds: featured tier when the pack has one (workbook),
// otherwise the most popular venues (open pack has no featured tier).
export function featuredPois(limit = 12): Poi[] {
  const featured = pois.filter((poi) => poi.datasetTier === "featured");
  if (featured.length > 0) return featured.slice(0, limit);
  return [...pois]
    .sort((left, right) => right.popularityScore - left.popularityScore)
    .slice(0, limit);
}
